### ISSUE TITLE
function inokation provide postgresql parameter types -> Check last comment

### ISSUE THREAD

**Issue by mmicek** [BezBartek/django-dynamic-from-clause#3]
In code: f"{source_sql % tuple(params)} AS {result[0]}" -> when params are datetime it must be in '...'  but for now there is without sign ' like integer.

Should be:
select * from get_date_range('2007-02-01', '2007-02-09');
Now is:
select * from get_date_range(2007-02-01, 2007-02-09);

**Comment by mmicek** [comment]
This was my mistake. I had to override template property of class Func, to provide ' signs,

**Comment by mmicek** [comment]
However the bug exists, but not in this code line. Here:
expression = expression_class(*(models.Value(arg) for arg in args))

Cannot wrap every arg in models.Value(). If i provide DateTime it shouldnt do it. I dont know how, but probalby you need to check arg type and pass proper object.

**Comment by BezBartek** [comment]
Fixed in version 0.0.6
The issue was with the way how we loaded parameters. Now we are following Django patterns in the clean way

Thank you for report
